version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: med
      POSTGRES_USER: med
      POSTGRES_PASSWORD: med
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: med
      DB_PASSWORD: med
      DB_NAME: med
    networks:
      - app-network

networks:
  app-network:
